name: 'Init'
description: 'Initialize the environment'

runs:
  using: 'composite'
  steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Detect Node version
        run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        # run: echo "##[set-output name=version;]$(cat .nvmrc)"
        id: nvmrc
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvmrc.outputs.version }}'
