name: Push

on:
  push:
    branches:
      - main

concurrency:
  group: push-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  pull:
    name: CI
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init
        id: push-init
        uses: ./.github/actions/init
